apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: my-volume
        configMap:
          name: test-data
      containers:
        - name: mongodb
          image: mongo
      #    envFrom:
       #     - configMapRef:
        #        name: test-data
          volumeMounts:
          - name: my-volume
            mountPath: /home/test1.json
            subPath: test1.json
          ports:
            - containerPort: 27017
