apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: ghcr.io/hasretagaslan/devops/house:0.1
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service:27017/my-db
      imagePullSecrets:
        - name: your-docker-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo
spec:
  ports:
    - name: mongo
      port: 27017
  selector:
    app: mongo

